# Workflow name
name: Github Actions
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
        - uses: actions/checkout@v3
        - run: echo "The ${{ github.repository }} repository has been cloned."
        - run: echo "Setting up JDK" 
        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Setup Android SDK
          uses: android-actions/setup-android@v3
        - name: Setup Gradle Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
        - run: echo "The workflow is now ready to test your code."
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - run: echo "Building Debug APK."  
        - name: Build with Gradle
          run: ./gradlew build
        - name: Run Linters and Test
          run: ./gradlew check
        - name: Upload Reports
          uses: actions/upload-artifact@v2
          with:
            name: Test-Reports
            path: app/build/reports
          if: always()
        - run: echo "Build status report=${{ job.status }}."
